### ISSUE TITLE
Builder::XmlMarkup is not explicitly required

### ISSUE THREAD

**Issue by swistak** [minitest-reporters/minitest-reporters#297] opened 2019-12-13 21:48 UTC
Hello.

There's a problem with the reporter in new Raisl versions that use zeitwerk loader.

Manifests with:

```
/path/to/app/vendor/bundle/ruby/2.6.0/gems/minitest-reporters-1.4.2/lib/minitest/reporters/junit_reporter.rb:51:in `block in report': uninitialized constant Builder::XmlMarkup (NameError)
```

This is a result of non-standard naming scheme of files I think (and is a at a core problem of a `builder` gem), however it can be easilly fixed with explicit require:

```
require 'builder/xmlmarkup'
```

**Comment by itsliamegan** [comment] 2021-01-18 16:42
I can't reproduce this error on rails v6.1.1, minitest-reporters 1.4.2, and ruby 2.6.0. Can you provide some steps to reproduce?

**Comment by barrettkingram** [comment] 2022-11-07 15:36
Closing this out for now but happy to reopen if reproduction steps are provided.

**Closed by barrettkingram** 2022-11-07 15:36 UTC
